title: Joshua Miller's Resume
email: resume@joshuadmiller.info
site-description: This is the site description
baseurl: ""
url:
sass:
    style: compressed
compress_html:    
  clippings: all  
  endings: all
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: all