title: A Resume
email: resume@joshuadmiller.info
site-description: This is the site description
in-development: true
baseurl: ""
url:

sass:
    style: compressed
  
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: all